language: nix

sudo: false

env:
  global:
    - CACHIX_CACHE=fgaz
    - NUR_REPO=fgaz

install:
 - nix --version
 - travis_retry nix-channel --update
 - nix-env -if https://github.com/cachix/cachix/tarball/master --substituters https://cachix.cachix.org --trusted-public-keys cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM=
 - cachix use "${CACHIX_CACHE}"

script:
 - export outs=$(nix-build non-broken.nix)
 - echo Produced $outs

after_success:
  - cachix push "${CACHIX_CACHE}" $outs
  - curl -XPOST "https://nur-update.herokuapp.com/update?repo=${NUR_REPO}"

